/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv --include-runtime=false cloudflare-env.d.ts` (hash: 965ab8b2862aab6347ae794ba8cd71bc)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./.open-next/worker");
  }
  interface Env {
    IMAGE_BUCKET: R2Bucket;
    DB: D1Database;
    ASSETS: Fetcher;
    NEXTJS_ENV: string;
  }
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "NEXTJS_ENV">
  > {}
}
