/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=staging --include-runtime=false --env-interface=CloudflareEnv` (hash: db6228c68c8c91b7641e5891f88e5bf0)
interface __BaseEnv_CloudflareEnv {
	PAGES_BUCKET: R2Bucket;
	ENVIRONMENT: "staging";
	ROBOTS_MODE: "noindex";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "ROBOTS_MODE">> {}
}
