/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=staging --include-runtime=false --env-interface=CloudflareEnv` (hash: c922d049ea125771d44e64c086e5be8b)
interface __BaseEnv_CloudflareEnv {
	PAGES_BUCKET: R2Bucket;
	ENVIRONMENT: "staging";
	ROBOTS_MODE: "noindex";
	CACHE_VERSION: "migration-local-004";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "ROBOTS_MODE" | "CACHE_VERSION">> {}
}
